version: '3'

services:
  elasticsearch:
    build:
      context: docker/elasticsearch/
      args:
        ELASTICSEARCH_VERSION: $ELK_VERSION
    volumes:
    - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - elk

  logstash:
    build:
      context: docker/logstash/
      args:
        LOGSTASH_VERSION: $ELK_VERSION
    volumes:
    - ./docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - ./docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
    - "5000:5000"
    - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
    - elk
    depends_on:
    - elasticsearch

  kibana:
    build:
      context: docker/kibana/
      args:
        KIBANA_VERSION: $ELK_VERSION
    volumes:
    - ./docker/kibana/config/:/usr/share/kibana/config:ro
    ports:
    - "5601:5601"
    networks:
    - elk
    depends_on:
    - elasticsearch

  metrics-app:
    build:
      context: ./
      args:
        JAR_HOME: build/libs
        RUN_SCRIPT: docker/app
    environment:
    - LOGSTASH_HOST
    - LOG_ENABLE_STASH
    - LOG_ENABLE_JSON
    ports:
    - "8080:8080"
    depends_on:
    - logstash
    command: ["./wait-for-it.sh", "-t", "60", "$LOGSTASH_HOST", "--", "./start.sh"]
    networks:
    - elk

  prometheus:
    build:
      context: ./docker/prometheus
      args:
        PROMETHEUS_VER: $PROMETHEUS_VER
    environment:
    - LOGSTASH_HOST
    ports:
    - "9090:9090"
    depends_on:
    - metrics-app
    networks:
    - elk

  grafana:
    build:
      context: ./docker/grafana
      args:
        GRAFANA_VER: $GRAFANA_VER
    environment:
    - GRAFANA_VER
    ports:
    - "3000:3000"
    networks:
    - elk

networks:
  elk:
    driver: bridge