ARG KIBANA_VERSION

# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:${KIBANA_VERSION}

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
